### PR TITLE
Updated format for latest 1.13 pre-release functioning and added 1.13 mob heads too

### PR DESCRIPTION
**Pull request by carlpoole**
I may have tweaked some drop rates, and ones I picked for 1.13 were best guess based on similar mobs and farming method required. Dolphins I set to 100% drop rate since dolphins can't be easily farmed and I wanted to deter it on my server.

### CODE REVIEW

**Comment by jarsworldcom** [comment]
Thanks for this.

What is the drop rate for Parrots?

**Comment by carlpoole** [comment]
@jarsworldcom I think its supposed to be 100%, looking at the loot table files. But I just tried this on my server (RIP chirpy) and a head didn't drop. I think it might be a problem with the variants functions compatibility with 1.13. I'll see if I can figure out what it might be

**Comment by jarsworldcom** [comment]
I thought it was supposed to be 100% as well.

**Comment by carlpoole** [comment]
@jarsworldcom I just fixed this and tested it. It was because the file structure was modified and I tweaked the advancement to enable it properly now!

**Comment by jarsworldcom** [comment]
Just tested it.  Out of the 50 test kills I got 2 cats heads.

**Comment by carlpoole** [comment]
@jarsworldcom That sounds about right, it looks like ocelot/cats are 5% drop rate so 5 out of 100 or 2/3 out of 50. You can adjust the drop rates by going into the loot_table json files and changing the value on this line:

`"chance": 0.05,`

**Comment by jarsworldcom** [comment]
Sorry, I got the cats heads from parrot kills.

**Comment by carlpoole** [comment]
@jarsworldcom oh, weird! Trying to see if I can find out why.

**Comment by jarsworldcom** [comment]
Thanks.

I still need to test out for the Iron Golem, Snow Golem, Elder Guardian, and Wither, but so far the Enderman and Rabbits don't drop with a 1000 looting sword.  Everything besides the parrots works.  Haven't tested for every variation.

**Comment by carlpoole** [comment]
@jarsworldcom Thanks for testing, thats really helpful. I found the issue with rabbits and changed the tag and re-tested and it seems to work now. Enderman is the drop rate I think, its `0.0002` so once I made a "looting 10k" sword I got a head. I think it was set that low because of Enderman farms. I just tested the golems, elder guardian, and wither and got heads.

I tried to reproduce the parrot/cat head problem, I killed about 100 parrots and got 100 parrot heads, so I'm not sure. How did you test it?

For testing I make changes to the code, delete the old datapack in my save folder, copy the new one over, then in game I run this:

```
/datapack disable "file/moremobheads"
/datapack enable "file/moremobheads"
/reload
```

And the changes from my code edits are in effect. I didn't get any cat heads so maybe I am not testing the same way

**Comment by jarsworldcom** [comment]
Thanks.

For the parrots I used a looting 3 sword.

For everything else I used a 1k sword.  I will try the 10k, as I haven't gotten a wither head to drop.  Everything else.

I always delete the folder to prevent issues.

I will again after work.

**Comment by jarsworldcom** [comment]
Got it all to work.  Thanks. :)

**Comment by carlpoole** [comment]
@jarsworldcom just FYI I just improved the naming of the heads so they dont change back to "Player Head" when placed and broken. Also the jeb sheep and toast rabbit were broken so I fixed them too.

**Comment by jarsworldcom** [comment]
Excellent work.  Didn't know they would change back to player head.

I am limited on time, but I tested it again for more of the variants.

Got a few of the colored sheep, rabbits, and wither heads.  Got 7 ocelot heads, and no variants.  I have never seen a wild ocelot, and wasn't able to tame it.  Don't think that really matters.

Need to test the villagers and llamas.  How do we get error?

**Comment by x1R1SHN1NJAx** [comment]
so weird thing im using this on a server and i dropped the more mob heads folder into my data packs folder. like you should. i did /reload and it registers under datapack list. but for some reason i cannot for the life of me get a mob to drop a head. tried parrots and vindicators. both have really high drop rates and i have tried a buttload of other mobs also. any idears?

**Comment by ChadDerion** [comment]
Can anybody clearify if it works in server using 1.13 officiel Minecraft server jar?

**Comment by carlpoole** [comment]
@x1R1SHN1NJAx make sure you download it from here https://github.com/carlpoole/moremobheads-1.13-datapack/archive/master.zip and copy the directory in that zip into datapacks. This is a pull request for my fixes from my forked repo so maybe you downloaded the one from this repo that doesn't currently work?

@ChadDerion Yep it works now, use this download and copy the directory inside into your datapacks folder

**Comment by ChadDerion** [comment]
The zip or the files in the zip?

And Also how to activate? :)

tor. 26. jul. 2018 19.30 skrev Carl Poole <notifications@github.com>:

**Comment by carlpoole** [comment]
@ChadDerion the "moremobheads" folder in the zip needs to be copied across

**Pull request closed without merging**
